"""Poses base dos herois (16x24, olhando para a direita).

Cada mapa e a pose ociosa; as 12 poses da folha saem de `build_frames`.
A camada de arma existe separada porque o golpe a move sozinha.

Duas licoes da primeira iteracao, validas para todo sprite deste projeto:

1. **Silhueta antes de detalhe.** Em 16 pixels de largura, o que identifica o
   personagem e o contorno -- chapeu pontudo, escudo largo, ombreira. Preencher
   a area toda de uma cor so produz um bloco colorido com rosto.
2. **A arma precisa de massa.** Um escudo de 2 pixels de largura le como um
   graveto flutuando. Adereco que define a classe ocupa espaco.

Convencao de leitura: a base ocupa a linha 23, centralizada -- e o que faz o
sprite pisar no chao em vez de flutuar (contracts/assets-sprites.md 1).
"""

from sprite_lib import Pose

_EMPTY = ["." * 16 for _ in range(24)]

# Vanguard -- tanque. Escudo largo a frente e ombreiras: e quem provoca, e a
# silhueta tem de ser a mais pesada do time. A espada curta passa por cima do
# escudo no golpe.
VANGUARD = Pose(
    body=[
        "................",
        "................",
        ".kkkkkk.........",
        "kmmmmmmk........",
        "kmhhhhmk........",
        "kmkkkkmk........",
        "knmmmmmk........",
        ".knmmmk.........",
        ".kkkkkk.........",
        "kkmmmmkk.kkkkkk.",
        "kmnuuunmk.kmmmmk",
        "knuuuuunk.kmggmk",
        "knuuuuunkkkmgymk",
        "knuuuuunk.kmggmk",
        "knnuuunnk.kmmmmk",
        ".knuuunk..kmmmmk",
        ".kdddddk..kmnnmk",
        ".kmmkkmk...kmmk.",
        ".knk.kmk....kk..",
        ".knk.kmk........",
        ".knk.kmk........",
        ".knk.kmk........",
        "knnk.kmmk.......",
        "kkkk.kkkk.......",
    ],
    weapon=[
        "................",
        "................",
        "................",
        "................",
        "..........kk....",
        "..........kmk...",
        "..........kmk...",
        "..........kmk...",
        "..........kmk...",
        "..........khk...",
        "..........kgk...",
        "..........kbk...",
        "..........kk....",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
)

# Elementalist -- dano magico em area. Chapeu pontudo e manto estreito dao a
# silhueta; o orbe do cajado e a leitura a distancia.
ELEMENTALIST = Pose(
    body=[
        ".....kk.........",
        "....kpqk........",
        "....kpqk........",
        "...kppqqk.......",
        "..kpppqqqk......",
        ".kkkkkkkkkk.....",
        "...k1111k.......",
        "..k112211k......",
        "..k1k11k1k......",
        "...k1111k.......",
        "....kkkk........",
        "...kppppk.......",
        "..kppqqppk......",
        "..kpaqqapk......",
        "..kppqqppk......",
        "..kppqqppk......",
        "..kppqqppk......",
        "..kppqqppk......",
        ".kpppqqpppk.....",
        ".kpqppqppqk.....",
        ".kpppqqpppk.....",
        "kppqqqqqqppk....",
        "kpqqqqqqqqpk....",
        "kkkkkkkkkkkk....",
    ],
    weapon=[
        "................",
        "................",
        "................",
        "...........kkk..",
        "..........kaaak.",
        "..........kajak.",
        "..........kaaak.",
        "...........kkk..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kok..",
        "...........kik..",
        "...........kik..",
        "...........kik..",
        "...........kkk..",
    ],
)

# Sharpshooter -- dano a distancia. Capuz e arco: a silhueta do arco a frente e
# o que o distingue do Tracker, que tambem usa capuz.
SHARPSHOOTER = Pose(
    body=[
        "................",
        "................",
        "..kkkkkk........",
        ".kfeeeeek.......",
        ".kfeeeeek.......",
        ".kf1111ek.......",
        ".kf1kk11k.......",
        "..k11111k.......",
        "..kkkkkk........",
        ".kfeeeeefk......",
        ".kfebbbefk......",
        ".kfebbbefk......",
        "..kebbbek.......",
        "..kebbbek.......",
        "..kfeeefk.......",
        "..kdddddk.......",
        "..kbbbbbk.......",
        "..kbbkbbk.......",
        "..kbk.kbk.......",
        "..kbk.kbk.......",
        "..kbk.kbk.......",
        "..kbk.kbk.......",
        ".kdbk.kbdk......",
        ".kkkk.kkkk......",
    ],
    weapon=[
        "................",
        "................",
        "................",
        ".........kk.....",
        "........kok.....",
        ".......kok......",
        ".......kok......",
        "......kok.......",
        "......kok.......",
        "......kok.......",
        "......kok.......",
        "......kok.......",
        "......kok.......",
        "......kok.......",
        "......kok.......",
        ".......kok......",
        ".......kok......",
        "........kok.....",
        ".........kk.....",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
)

# Medtech -- suporte. Tons claros e frasco: e o unico do time sem arma pesada,
# e a leitura precisa dizer isso de longe.
MEDTECH = Pose(
    body=[
        "................",
        "................",
        "..kkkkkk........",
        ".kwwwwwwk.......",
        ".kw1111wk.......",
        ".kw1kk11k.......",
        ".kw11111k.......",
        "..k11111k.......",
        "..kkkkkk........",
        ".kwwwwwwwk......",
        ".kwwexewwk......",
        ".kweeeeewk......",
        ".kwwexewwk......",
        ".kwwwwwwwk......",
        ".kwwwwwwwk......",
        ".kxwwwwwxk......",
        "..kwwwwwk.......",
        "..kwwkwwk.......",
        "..kwk.kwk.......",
        "..kwk.kwk.......",
        "..kwk.kwk.......",
        "..kwk.kwk.......",
        ".kxwk.kwxk......",
        ".kkkk.kkkk......",
    ],
    weapon=[
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "..........kkk...",
        ".........kaaak..",
        ".........ka4ak..",
        ".........ka4ak..",
        ".........kaaak..",
        "..........kkk...",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
)

# Tracker -- corpo a corpo veloz. Adagas gemeas e silhueta leve; bate quase o
# dobro dos outros, entao a pose e inclinada para a frente.
TRACKER = Pose(
    body=[
        "................",
        "................",
        "...kkkkk........",
        "..kdbbbbk.......",
        "..kdb111k.......",
        "..kdb1k1k.......",
        "..kd1111k.......",
        "...k1111k.......",
        "...kkkkk........",
        "..kdbbbbbk......",
        "..kdb444bk......",
        "..kdbbbbbk......",
        "...kbbbbk.......",
        "...kbbbbk.......",
        "...kdbbdk.......",
        "...kddddk.......",
        "...kbbbbk.......",
        "...kbbkbk.......",
        "...kbk.kbk......",
        "...kbk.kbk......",
        "..kbk..kbk......",
        "..kbk..kbk......",
        ".kdbk..kbdk.....",
        ".kkkk..kkkk.....",
    ],
    weapon=[
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "..........kk....",
        ".........khk....",
        ".........khk....",
        ".........kmk....",
        "..........kk....",
        "..........kk....",
        ".........khk....",
        ".........khk....",
        ".........kmk....",
        "..........kk....",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
)

# Berserker -- bruto. Sem armadura, machado com massa, ombros largos: fica mais
# forte com HP baixo, e a silhueta e a mais agressiva do time.
BERSERKER = Pose(
    body=[
        "................",
        "................",
        "..kkkkkk........",
        ".ktrrrrtk.......",
        ".ktr1111k.......",
        ".ktr1kk1k.......",
        ".kt11111k.......",
        "..k1t1t1k.......",
        "..kkkkkk........",
        "kk1111111kk.....",
        "k1122211221k....",
        "k1122211221k....",
        ".k1121121k......",
        ".k1122211k......",
        ".k1112111k......",
        ".kdddddddk......",
        ".kbbbbbbbk......",
        ".kbbbkbbbk......",
        ".kbbk.kbbk......",
        ".k1bk.kb1k......",
        ".k11k.k11k......",
        ".k11k.k11k......",
        "kd11k.k11dk.....",
        "kkkkk.kkkkk.....",
    ],
    weapon=[
        "................",
        "................",
        "................",
        "................",
        ".........kkkk...",
        ".........kmmmk..",
        "........khmmmmk.",
        "........khmmmmk.",
        ".........kmmmk..",
        ".........kkbkk..",
        "..........kbk...",
        "..........kbk...",
        "..........kbk...",
        "..........kbk...",
        "..........kbk...",
        "..........kdk...",
        "..........kdk...",
        "..........kkk...",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
)

HEROES = {
    "vanguard": VANGUARD,
    "elementalist": ELEMENTALIST,
    "sharpshooter": SHARPSHOOTER,
    "medtech": MEDTECH,
    "tracker": TRACKER,
    "berserker": BERSERKER,
}
